services:
  laravel:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    container_name: portfolio_laravel
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
